### ISSUE TITLE
hifive: TIMER0001 test isn't working (it passes instantly instead of taking 3 seconds)

### ISSUE THREAD

**Issue by kent-mcleod** [seL4/sel4test#91]
Can be observed by the logs (with timestamps enabled). The test completes instantly, but it's expected to take 3 seconds.

```
Sun, 23 Apr 2023 06:11:03 GMT   	<testcase classname="sel4test" name="TIMER0001">
Sun, 23 Apr 2023 06:11:03 GMT   	</testcase>
Sun, 23 Apr 2023 06:11:03 GMT   	<testcase classname="sel4test" name="TIMER0002">
Sun, 23 Apr 2023 06:11:03 GMT   	</testcase>
Sun, 23 Apr 2023 06:11:03 GMT
```

**Comment by Indanz** [comment]
Fixed with [this fix](https://github.com/seL4/util_libs/pull/165) in util_libs.

What happened was that the overflow IRQ triggered, but before it is handled pwm_get_time() was called, which also checks and handles overflows in case IRQs got missed. Then the IRQ handler incremented `time_h` again, making the software think all timers expired immediately.

**Comment by lsf37** [comment]
Nice!
